include/suppress_messages.inc
# Connection 1 suppresses message <Found .* prepared XA transactions>.
# Connection 1 suppresses message <.*Checksum mismatch in datafile.*>.
CREATE TABLE t1 (c1 INT PRIMARY KEY);
XA START X'78696431',X'',1;
INSERT INTO t1 VALUES (2);
XA END X'78696431',X'',1;
XA PREPARE X'78696431',X'',1;
XA COMMIT X'78696431',X'',1;
include/save_binlog_position.inc
XA START X'78696431',X'',1;
INSERT INTO t1 VALUES (1);
XA END X'78696431',X'',1;
XA PREPARE X'78696431',X'',1;
include/execute_to_conditional_timestamp_sync_point.inc [before_gtid_externalization]
XA ROLLBACK X'78696431',X'',1;
SET SESSION debug = '+d,crash_now_safe';
ERROR HY000: Lost connection to MySQL server during query
ERROR HY000: Lost connection to MySQL server during query
# restart
include/assert.inc [Found 1 log message(s) for "in InnoDB engine. No attempts to commit, rollback or prepare any transactions."]
include/assert_binlog_events.inc [Gtid # Query/XA START X'78696431',X'',1 # Table_map # Write_rows # Query/XA END X'78696431',X'',1 # XA_prepare/XA PREPARE X'78696431',X'',1 # Gtid # Query/XA ROLLBACK X'78696431',X'',1]
include/assert.inc [GTID_EXECUTED has been updated]
include/assert.inc [No XA transactions in PREPARED state]
include/assert.inc [Table 'test.t1' record count must be 1]
DROP TABLE t1;
